name: 'Inject Terraform Variables from Azure Key Vault'
description: 'Determines Key Vault name, authenticates to Azure, and injects TF-VAR-* secrets as environment variables'
author: 'Michael Patsula'

inputs:
  environment_folders:
    required: true
    description: 'Space-separated list of environment folder names'
  kv_names:
    required: true
    description: 'Space-separated list of Key Vault names'
  current_environment:
    required: true
    description: 'Current environment folder name (from matrix)'
  azure_client_id:
    required: true
    description: 'Azure Client ID for OIDC authentication'
  azure_tenant_id:
    required: true
    description: 'Azure Tenant ID for OIDC authentication'
  azure_subscription_id:
    required: true
    description: 'Azure Subscription ID for OIDC authentication'

runs:
  using: composite
  steps:
    - name: 'Determine Key Vault Name'
      id: determine-kv-name
      shell: bash
      env:
        ENVIRONMENT_FOLDERS: ${{ inputs.environment_folders }}
        KV_NAMES: ${{ inputs.kv_names }}
        ENV_FOLDER: ${{ inputs.current_environment }}
      run: |
        if [ -z "$KV_NAMES" ]; then
          echo "ℹ️  No Key Vault names provided, skipping Key Vault secret injection"
          echo "kv_name=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Convert space-separated lists to arrays
        read -a ENV_ARRAY <<< "$ENVIRONMENT_FOLDERS"
        read -a KV_ARRAY <<< "$KV_NAMES"
        
        # Find the index of current environment in the environment folders list
        ENV_INDEX=-1
        for i in "${!ENV_ARRAY[@]}"; do
          if [ "${ENV_ARRAY[$i]}" = "$ENV_FOLDER" ]; then
            ENV_INDEX=$i
            break
          fi
        done
        
        if [ $ENV_INDEX -eq -1 ]; then
          echo "⚠️  Warning: Environment folder '$ENV_FOLDER' not found in environment_folders list"
          echo "ℹ️  Skipping Key Vault secret injection"
          echo "kv_name=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Get corresponding Key Vault name by index
        if [ $ENV_INDEX -lt ${#KV_ARRAY[@]} ]; then
          KV_NAME="${KV_ARRAY[$ENV_INDEX]}"
          echo "✅ Matched environment '$ENV_FOLDER' (index $ENV_INDEX) to Key Vault: $KV_NAME"
        else
          echo "⚠️  Warning: No Key Vault name found at index $ENV_INDEX for environment '$ENV_FOLDER'"
          echo "ℹ️  Key Vault names list has ${#KV_ARRAY[@]} entries, but environment is at index $ENV_INDEX"
          echo "ℹ️  Skipping Key Vault secret injection"
          echo "kv_name=" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "kv_name=$KV_NAME" >> $GITHUB_OUTPUT
        echo "🔍 Using Key Vault: $KV_NAME"

    - name: Azure Login (OIDC)
      if: steps.determine-kv-name.outputs.kv_name != ''
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: 'Fetch and Inject TF_VARS from Azure Key Vault'
      if: steps.determine-kv-name.outputs.kv_name != ''
      shell: bash
      env:
        KV_NAME: ${{ steps.determine-kv-name.outputs.kv_name }}
      run: |
        # Azure CLI is pre-installed on ubuntu-latest runners
        # Verify Azure CLI is available
        if ! command -v az &> /dev/null; then
          echo "❌ Error: Azure CLI (az) is not available"
          exit 1
        fi
        
        # 1. Verify Key Vault exists and is accessible
        echo "🔍 Checking if Key Vault exists: $KV_NAME"
        if ! az keyvault show --name "$KV_NAME" >/dev/null 2>&1; then
          echo "❌ Error: Key Vault '$KV_NAME' not found or not accessible"
          echo "Please verify the Key Vault name is correct and the service principal has access."
          exit 1
        fi
        
        # 2. Get a list of all secret names from the vault
        echo "🔍 Searching for TF-VAR secrets in Key Vault: $KV_NAME"
        SECRET_NAMES=$(az keyvault secret list --vault-name "$KV_NAME" --query "[].name" -o tsv 2>/dev/null || echo "")
        
        if [ -z "$SECRET_NAMES" ]; then
          echo "ℹ️  No secrets found in Key Vault or Key Vault not accessible"
          exit 0
        fi
        
        FOUND_COUNT=0
        for NAME in $SECRET_NAMES; do
          if [[ $NAME == TF-VAR-* ]]; then
            # 2. Get the actual secret value (preserves newlines)
            VALUE=$(az keyvault secret show --vault-name "$KV_NAME" --name "$NAME" --query "value" -o tsv 2>/dev/null || echo "")
            
            if [ -z "$VALUE" ]; then
              echo "⚠️  Warning: Could not retrieve secret: $NAME"
              continue
            fi
            
            # 3. Transform name for Terraform (TF-VAR-db-pass -> TF_VAR_db_pass)
            ENV_NAME=$(echo "$NAME" | tr '-' '_')

            # 4. Register masks line-by-line for security
            # This ensures every line of a multi-line secret is redacted in logs
            while IFS= read -r line; do
              if [ -n "$line" ]; then
                echo "::add-mask::$line"
              fi
            done <<< "$VALUE"

            # 5. Simplified Heredoc Injection
            # The { } block opens GITHUB_ENV once for all lines in the block
            {
              echo "${ENV_NAME}<<SECRET_EOF"
              echo "$VALUE"
              echo "SECRET_EOF"
            } >> "$GITHUB_ENV"
            
            echo "✅ Injected $ENV_NAME (from Key Vault secret: $NAME)"
            FOUND_COUNT=$((FOUND_COUNT + 1))
          fi
        done
        
        if [ $FOUND_COUNT -eq 0 ]; then
          echo "ℹ️  No secrets found with TF-VAR- prefix in Key Vault"
        else
          echo "✅ Successfully injected $FOUND_COUNT Terraform variable(s) from Key Vault"
        fi
