name: Helm Chart Verify and Publish (Reusable)

on:
  workflow_call:
    inputs:
      chart_path:
        description: 'Path to Helm chart directory'
        required: true
        type: string
      chart_name:
        description: 'Chart name (defaults to directory name)'
        required: false
        type: string
      registry:
        description: 'OCI registry URL for publishing chart'
        required: false
        type: string
      publish_chart:
        description: 'Whether to publish the chart'
        required: false
        type: boolean
        default: false
      helm_version:
        description: 'Helm version to use'
        required: false
        type: string
        default: '3.12.0'
    secrets:
      REGISTRY_USERNAME:
        description: 'Registry username for publishing'
        required: false
      REGISTRY_PASSWORD:
        description: 'Registry password or token for publishing'
        required: false

jobs:
  helm-verify-publish:
    name: Helm Chart Verify and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    outputs:
      chart_version: ${{ steps.chart-version.outputs.version }}
      chart_name: ${{ steps.chart-name.outputs.name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ inputs.helm_version }}

      - name: Extract chart name
        id: chart-name
        run: |
          if [ -n "${{ inputs.chart_name }}" ]; then
            echo "name=${{ inputs.chart_name }}" >> $GITHUB_OUTPUT
          else
            CHART_NAME=$(basename "${{ inputs.chart_path }}")
            echo "name=$CHART_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Extract chart version
        id: chart-version
        run: |
          VERSION=$(helm show chart ${{ inputs.chart_path }} | grep '^version:' | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "ðŸ“‹ Chart version from Chart.yaml: $VERSION"

      - name: Lint Helm chart
        run: |
          helm lint ${{ inputs.chart_path }}
          echo "âœ… Helm chart linting passed"

      - name: Validate Helm chart
        run: |
          helm template test-release ${{ inputs.chart_path }} --debug --dry-run
          echo "âœ… Helm chart template validation passed"

      - name: Check chart dependencies
        run: |
          if [ -f "${{ inputs.chart_path }}/Chart.yaml" ] && grep -q "dependencies:" "${{ inputs.chart_path }}/Chart.yaml"; then
            helm dependency build ${{ inputs.chart_path }}
            echo "âœ… Helm chart dependencies built"
          else
            echo "â„¹ï¸  No dependencies found in chart"
          fi

      - name: Package Helm chart
        id: package
        run: |
          helm package ${{ inputs.chart_path }}
          CHART_FILE=$(ls -t *.tgz | head -1)
          echo "file=$CHART_FILE" >> $GITHUB_OUTPUT
          echo "ðŸ“¦ Chart packaged: $CHART_FILE"

      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: ${{ steps.package.outputs.file }}
          retention-days: 30

      - name: Log in to OCI registry
        if: inputs.publish_chart && inputs.registry != ''
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | helm registry login ${{ inputs.registry }} \
            -u ${{ secrets.REGISTRY_USERNAME }} \
            --password-stdin

      - name: Publish Helm chart to OCI registry
        if: inputs.publish_chart && inputs.registry != ''
        run: |
          CHART_FILE="${{ steps.package.outputs.file }}"
          CHART_NAME="${{ steps.chart-name.outputs.name }}"
          CHART_VERSION="${{ steps.chart-version.outputs.version }}"
          
          # Load and push to OCI registry
          helm push $CHART_FILE oci://${{ inputs.registry }}/$CHART_NAME
          echo "âœ… Chart published to oci://${{ inputs.registry }}/$CHART_NAME:$CHART_VERSION"

      - name: Chart publish summary
        if: inputs.publish_chart && inputs.registry != ''
        run: |
          echo "### ðŸ“¦ Helm Chart Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Chart**: ${{ steps.chart-name.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.chart-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry**: oci://${{ inputs.registry }}/${{ steps.chart-name.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **File**: ${{ steps.package.outputs.file }}" >> $GITHUB_STEP_SUMMARY

